#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-future.apply
Version  : 1.10.0
Release  : 9
URL      : https://cran.r-project.org/src/contrib/future.apply_1.10.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/future.apply_1.10.0.tar.gz
Summary  : Apply Function to Elements in Parallel using Futures
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-future
Requires: R-globals
BuildRequires : R-future
BuildRequires : R-globals
BuildRequires : buildreq-R

%description
No detailed description available

%prep
%setup -q -n future.apply
cd %{_builddir}/future.apply

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1667850128

%install
export SOURCE_DATE_EPOCH=1667850128
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/future.apply/CITATION
/usr/lib64/R/library/future.apply/DESCRIPTION
/usr/lib64/R/library/future.apply/INDEX
/usr/lib64/R/library/future.apply/Meta/Rd.rds
/usr/lib64/R/library/future.apply/Meta/features.rds
/usr/lib64/R/library/future.apply/Meta/hsearch.rds
/usr/lib64/R/library/future.apply/Meta/links.rds
/usr/lib64/R/library/future.apply/Meta/nsInfo.rds
/usr/lib64/R/library/future.apply/Meta/package.rds
/usr/lib64/R/library/future.apply/Meta/vignette.rds
/usr/lib64/R/library/future.apply/NAMESPACE
/usr/lib64/R/library/future.apply/NEWS.md
/usr/lib64/R/library/future.apply/R/future.apply
/usr/lib64/R/library/future.apply/R/future.apply.rdb
/usr/lib64/R/library/future.apply/R/future.apply.rdx
/usr/lib64/R/library/future.apply/WORDLIST
/usr/lib64/R/library/future.apply/doc/future.apply-1-overview.html
/usr/lib64/R/library/future.apply/doc/future.apply-1-overview.md.rsp
/usr/lib64/R/library/future.apply/doc/index.html
/usr/lib64/R/library/future.apply/help/AnIndex
/usr/lib64/R/library/future.apply/help/aliases.rds
/usr/lib64/R/library/future.apply/help/future.apply.rdb
/usr/lib64/R/library/future.apply/help/future.apply.rdx
/usr/lib64/R/library/future.apply/help/paths.rds
/usr/lib64/R/library/future.apply/html/00Index.html
/usr/lib64/R/library/future.apply/html/R.css
/usr/lib64/R/library/future.apply/tests/fold.R
/usr/lib64/R/library/future.apply/tests/future_apply.R
/usr/lib64/R/library/future.apply/tests/future_by.R
/usr/lib64/R/library/future.apply/tests/future_eapply.R
/usr/lib64/R/library/future.apply/tests/future_lapply,RNG.R
/usr/lib64/R/library/future.apply/tests/future_lapply,globals.R
/usr/lib64/R/library/future.apply/tests/future_lapply.R
/usr/lib64/R/library/future.apply/tests/future_mapply,globals.R
/usr/lib64/R/library/future.apply/tests/future_mapply.R
/usr/lib64/R/library/future.apply/tests/future_replicate.R
/usr/lib64/R/library/future.apply/tests/future_sapply.R
/usr/lib64/R/library/future.apply/tests/future_tapply.R
/usr/lib64/R/library/future.apply/tests/future_vapply.R
/usr/lib64/R/library/future.apply/tests/globals,tricky_recursive.R
/usr/lib64/R/library/future.apply/tests/incl/end.R
/usr/lib64/R/library/future.apply/tests/incl/start,load-only.R
/usr/lib64/R/library/future.apply/tests/incl/start.R
/usr/lib64/R/library/future.apply/tests/rng.R
/usr/lib64/R/library/future.apply/tests/stdout.R
/usr/lib64/R/library/future.apply/tests/utils.R
